### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by khw11044** [xyshi2000/SpikingResformer#6]
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    
--> spikingjelly\activation_based\auto_cuda\base.py"

elif value.dtype == np.int: --> int
 
 
![image](https://github.com/user-attachments/assets/931eac1e-f3e1-45d2-bce3-aa7c3c8cb758)

**Comment by xyshi2000** [comment]
This is caused by the spikingjelly package. You can modify the np.int to np.int_ manually.
