### ISSUE TITLE
matmul

### ISSUE THREAD

**Issue by 2ephyrus** [xyshi2000/SpikingResformer#7]
```
    def cal_sop_matmul(self, left: Tensor, right: Tensor, m: SpikingMatmul):
        with torch.no_grad():
            if m.spike == 'l': right = torch.ones_like(right)
            elif m.spike == 'r': left = torch.ones_like(left)
            elif m.spike == 'both': pass
            else: raise ValueError(m.spike)
            out = torch.matmul(left, right)
            return out.sum().unsqueeze(0)
```
请问为什么matmul使用‘r’参数而不是both来记录实际的矩阵运算？

**Comment by xyshi2000** [comment]
spike参数用来指定哪一个为脉冲矩阵，'r'表示右矩阵为脉冲矩阵，'both'表示左右均为脉冲矩阵。一个简单的理解方式是：假设右矩阵为脉冲矩阵，如果将左矩阵看做权重矩阵，此时SOPs的计算方式与线性层是相似的

**Comment by 2ephyrus** [comment]
感谢您的回复！
根据我的理解，您论文中对SOPs的计算和Spikformer中的定义式应该是一致的？
![image](https://github.com/user-attachments/assets/bf6aec52-9d1c-4871-9f44-8e7245a68d64)
1. 根据我对您的代码理解，FLOPs的计算是基于计算公式，而SOPs则是利用矩阵与矩阵（权重）的乘积（次数）来近似。请问SOPs对FLOPs的估算与实际的计算公式结果差距大吗？如果差距不大，为什么FLOPs的计算不采用同样的方法（权重或矩阵置1），因为这种计算方法十分巧妙。
2. 根据Spikformer中的描述，SOPs等于FLOPs乘以电位值。这样做为什么是合理的？因为SNN仍然是在GPU上进行训练的，虽然它的激活函数是0/1性质，但是它的电位仍旧是浮点型，这和ANN中的运算没有差别？
3. SOPs的计算是否受到网络中SN位置和数量的影响？我的意思是，在卷积层的前（或后）加入（或移除）SN。我注意到，你的网络除了stem，卷积层的输入均为脉冲形式的矩阵，如果输入并不是脉冲形式，是否影响SOPs的计算？还是说，代码中对SOPs的计算式仍旧适用。

**Comment by 2ephyrus** [comment]
针对Q2，我补充一下我的理解，假设有个01矩阵，它与另一个矩阵进行矩阵运算，即使“0”的乘积毫无意义，但是机器仍然会执行这个无效的操作。本人不了解SNN的工作机理，恳求作者能够指点一下。

**Comment by 2ephyrus** [comment]
能耗的计算忽略了stem层，是为了简化计算还是stem层的能耗可以忽略不计？
